
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package ams11ghps;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LKEY = 33;
  public static final int COMMENT = 21;
  public static final int LPAREN = 31;
  public static final int SEMI = 28;
  public static final int INT = 39;
  public static final int MINUS = 24;
  public static final int STATIC = 6;
  public static final int RPAREN = 32;
  public static final int NOT = 26;
  public static final int AND = 18;
  public static final int INVERTBAR = 37;
  public static final int LESSTHAN = 19;
  public static final int COMMA = 30;
  public static final int CLASS = 3;
  public static final int DIFFERENT = 22;
  public static final int PLUS = 23;
  public static final int ASSIGN = 27;
  public static final int MAIN = 8;
  public static final int IF = 11;
  public static final int THIS = 15;
  public static final int DOT = 29;
  public static final int STRARG = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 13;
  public static final int EQUAL = 20;
  public static final int TRUE = 42;
  public static final int RKEY = 34;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int VOID = 7;
  public static final int LBRACK = 35;
  public static final int TIMES = 25;
  public static final int ELSE = 12;
  public static final int RBRACK = 36;
  public static final int WHILE = 10;
  public static final int PUBLIC = 4;
  public static final int EXTENDS = 5;
  public static final int STRING = 9;
  public static final int FALSE = 41;
  public static final int PRINT = 17;
  public static final int LENGTH = 14;
  public static final int IDENTIFIER = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "CLASS",
  "PUBLIC",
  "EXTENDS",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "LENGTH",
  "THIS",
  "NEW",
  "PRINT",
  "AND",
  "LESSTHAN",
  "EQUAL",
  "COMMENT",
  "DIFFERENT",
  "PLUS",
  "MINUS",
  "TIMES",
  "NOT",
  "ASSIGN",
  "SEMI",
  "DOT",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LKEY",
  "RKEY",
  "LBRACK",
  "RBRACK",
  "INVERTBAR",
  "STRARG",
  "INT",
  "IDENTIFIER",
  "FALSE",
  "TRUE"
  };
}

